# Generated by Django 3.1.1 on 2020-11-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_collection',
            name='Published_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
