# Generated by Django 3.1.1 on 2020-11-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmanager', '0002_books_collection_published_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_collection',
            old_name='Published_year',
            new_name='published_year',
        ),
    ]
