# Generated by Django 3.1.1 on 2020-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanager', '0003_auto_20201101_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='requested_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('requests', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='books_collection',
            name='book_id',
            field=models.IntegerField(unique=True),
        ),
    ]
