# Generated by Django 3.1.3 on 2020-11-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_books',
            name='roll_number',
            field=models.IntegerField(default=0),
        ),
    ]
